# Generated by Django 5.1.3 on 2024-11-26 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id_rol', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(choices=[('ADMIN', 'Administrador'), ('USER', 'Usuario')], default='USER', max_length=5)),
            ],
        ),
    ]
